services:
  dev:
    image: template-api-project:dev
    build:
      context: .
      target: dev
    container_name: template_project_dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  prod:
    image: template-api-project:prod
    build:
      context: .
      target: production
    container_name: template_project_prod
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
